### ISSUE TITLE
How to use this Extension?

### ISSUE THREAD

**Issue by curiosbasant** [bilalekremharmansa/SceneBuilderVSCodeExtension#2]
Please provide documentation for the extension.

**Comment by bilalekremharmansa** [comment]
I know it's not well documented but have you checked out [CHANGELOD.md](https://github.com/bilalekremharmansa/SceneBuilderVSCodeExtension/blob/master/CHANGELOG.md) ?

**Comment by bilalekremharmansa** [comment]
Hi,

I've published a new version of the extension. 

Please run the following instructions:
Go `Cmd+Alt+P`, 'Configure Scene Builder' thus will be open a window to select Scene Builder executable. Now, you configured the extension.

Open an FXML file and select 'Open in Scene Builder' command in command palette (Cmd+Alt+P).

Hopefully, you should be able to run the extension will no problem.

Feel free for any suggestions.
